CREATE TABLE REGIONS_BKP AS SELECT * FROM REGIONS;
CREATE TABLE COUNTRIES_BKP AS SELECT * FROM COUNTRIES;
CREATE TABLE LOCATIONS_BKP AS SELECT * FROM LOCATIONS;
CREATE TABLE WAREHOUSES_BKP AS SELECT * FROM WAREHOUSES;
CREATE TABLE DEPARTMENT_BKP AS SELECT * FROM DEPARTMENT;
CREATE TABLE EMPLOYEES_BKP AS SELECT * FROM EMPLOYEES;
CREATE TABLE PRODUCT_CATEGORY_BKP AS SELECT * FROM PRODUCT_CATEGORY;
CREATE TABLE PRODUCTS_BKP AS SELECT * FROM PRODUCTS;
CREATE TABLE INVENTORY_BKP AS SELECT * FROM INVENTORY;
CREATE TABLE CUSTOMERS_BKP AS SELECT * FROM CUSTOMERS;
CREATE TABLE CONTACTS_BKP AS SELECT * FROM CONTACTS;
CREATE TABLE ORDER_STATUS_BKP AS SELECT * FROM ORDER_STATUS;
CREATE TABLE ORDERS_BKP AS SELECT * FROM ORDERS;
CREATE TABLE ORDER_ITEMS_BKP AS SELECT * FROM ORDER_ITEMS;










 