-- Login as onlinestoredb & run below

CREATE TABLE onlinestoredb.REGIONS_BKP AS SELECT * FROM REGIONS;
CREATE TABLE onlinestoredb.COUNTRIES_BKP AS SELECT * FROM COUNTRIES;
CREATE TABLE onlinestoredb.LOCATIONS_BKP AS SELECT * FROM LOCATIONS;
CREATE TABLE onlinestoredb.WAREHOUSES_BKP AS SELECT * FROM WAREHOUSES;
CREATE TABLE onlinestoredb.DEPARTMENT_BKP AS SELECT * FROM DEPARTMENT;
CREATE TABLE onlinestoredb.EMPLOYEES_BKP AS SELECT * FROM EMPLOYEES;
CREATE TABLE onlinestoredb.PRODUCT_CATEGORY_BKP AS SELECT * FROM PRODUCT_CATEGORY;
CREATE TABLE onlinestoredb.PRODUCTS_BKP AS SELECT * FROM PRODUCTS;
CREATE TABLE onlinestoredb.INVENTORY_BKP AS SELECT * FROM INVENTORY;
CREATE TABLE onlinestoredb.CUSTOMERS_BKP AS SELECT * FROM CUSTOMERS;
CREATE TABLE onlinestoredb.CONTACTS_BKP AS SELECT * FROM CONTACTS;
CREATE TABLE onlinestoredb.ORDER_STATUS_BKP AS SELECT * FROM ORDER_STATUS;
CREATE TABLE onlinestoredb.ORDERS_BKP AS SELECT * FROM ORDERS;
CREATE TABLE onlinestoredb.ORDER_ITEMS_BKP AS SELECT * FROM ORDER_ITEMS;










 
