-- Login as "onlinestoredb" & run below

-- Remove Triggers
DROP TRIGGER TRG_ORDER_ITEMS_AUD;
DROP TRIGGER TRG_ORDERS_AUD;
DROP TRIGGER TRG_ORDER_STATUS_AUD;
DROP TRIGGER TRG_CONTACTS_AUD;
DROP TRIGGER TRG_CUSTOMERS_AUD;
DROP TRIGGER TRG_INVENTORY_AUD;
DROP TRIGGER TRG_PRODUCTS_AUD;
DROP TRIGGER TRG_PRODUCT_CATEGORY_AUD;
DROP TRIGGER TRG_EMPLOYEES_AUD;
DROP TRIGGER TRG_DEPARTMENT_AUD;
DROP TRIGGER TRG_WAREHOUSES_AUD;
DROP TRIGGER TRG_LOCATIONS_AUD;
DROP TRIGGER TRG_COUNTRIES_AUD;
DROP TRIGGER TRG_REGIONS_AUD;




-- Remove Audit tables
DROP TABLE ORDER_ITEMS_AUD;
DROP TABLE ORDERS_AUD;
DROP TABLE ORDER_STATUS_AUD;
DROP TABLE CONTACTS_AUD;
DROP TABLE CUSTOMERS_AUD;
DROP TABLE INVENTORY_AUD;
DROP TABLE PRODUCTS_AUD;
DROP TABLE PRODUCT_CATEGORY_AUD;
DROP TABLE EMPLOYEES_AUD;
DROP TABLE DEPARTMENT_AUD;
DROP TABLE WAREHOUSES_AUD;
DROP TABLE LOCATIONS_AUD;
DROP TABLE COUNTRIES_AUD;
DROP TABLE REGIONS_AUD;



-- Remove backup tables
DROP TABLE ORDER_ITEMS_BKP;
DROP TABLE ORDERS_BKP;
DROP TABLE ORDER_STATUS_BKP;
DROP TABLE CONTACTS_BKP;
DROP TABLE CUSTOMERS_BKP;
DROP TABLE INVENTORY_BKP;
DROP TABLE PRODUCTS_BKP;
DROP TABLE PRODUCT_CATEGORY_BKP;
DROP TABLE EMPLOYEES_BKP;
DROP TABLE DEPARTMENT_BKP;
DROP TABLE WAREHOUSES_BKP;
DROP TABLE LOCATIONS_BKP;
DROP TABLE COUNTRIES_BKP;
DROP TABLE REGIONS_BKP;


-- Remove main tables
DROP TABLE ORDER_ITEMS;
DROP TABLE ORDERS;
DROP TABLE ORDER_STATUS;
DROP TABLE CONTACTS;
DROP TABLE CUSTOMERS;
DROP TABLE INVENTORY;
DROP TABLE PRODUCTS;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE EMPLOYEES;
DROP TABLE DEPARTMENT;
DROP TABLE WAREHOUSES;
DROP TABLE LOCATIONS;
DROP TABLE COUNTRIES;
DROP TABLE REGIONS;


